name: automate.yml

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:

    branches:       #[ master ]
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - 'master'    # includes master
      - 'main'      # includes main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  printenv:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.08, macos-10.15, macos-latest, arm, self-hosted]
        python-version: ['3.8', '3.9']
        exclude:
          - os: ubuntu-latest
            python-version: ['2.7','3.6','3.7']
          - os: ubuntu-20.08
            python-version: ['2.7','3.6','3.7']
          - os: macos-latest
            python-version: ['2.7','3.6','3.7']
          - os: macos-10.15
            python-version: ['2.7','3.6','3.7']
          - os: windows-latest
            python-version: ['2.7','3.6','3.7']
          - os: self-hosted
            python-version: ['3.9']
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Setup Matrix
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Print github workspace
        run: |
          printenv
          cd $GITHUB_WORKSPACE
          make init

  automate:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.08, macos-10.15, macos-latest, arm, self-hosted]
          #python-version: ['3.8', '3.9']
        python-version: ['3.9']
        exclude:
          - os: ubuntu-latest
            python-version: ['2.7','3.6','3.7']
          - os: ubuntu-20.08
            python-version: ['2.7','3.6','3.7']
          - os: macos-latest
            python-version: ['2.7','3.6','3.7']
          - os: macos-10.15
            python-version: ['2.7','3.6','3.7']
          - os: windows-latest
            python-version: ['2.7','3.6','3.7']
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
            #- uses: actions/checkout@v2
            #  with:
            #    # Repository name with owner. For example, actions/checkout
            #    # Default: ${{ github.repository }}
            #    #repository: ''

            #    # The branch, tag or SHA to checkout. When checking out the repository that
            #    # triggered a workflow, this defaults to the reference or SHA for that event.
            #    # Otherwise, uses the default branch.
            #    #ref: 'master'

            #    # Personal access token (PAT) used to fetch the repository. The PAT is configured
            #    # with the local git config, which enables your scripts to run authenticated git
            #    # commands. The post-job step removes the PAT.
            #    #
            #    # We recommend using a service account with the least permissions necessary. Also
            #    # when generating a new PAT, select the least scopes necessary.
            #    #
            #    # [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
            #    #
            #    # Default: ${{ github.token }}
            #    #token: ''

            #    # SSH key used to fetch the repository. The SSH key is configured with the local
            #    # git config, which enables your scripts to run authenticated git commands. The
            #    # post-job step removes the SSH key.
            #    #
            #    # We recommend using a service account with the least permissions necessary.
            #    #
            #    # [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
            #    #ssh-key: ''

            #    # Known hosts in addition to the user and global host key database. The public SSH
            #    # keys for a host may be obtained using the utility `ssh-keyscan`. For example,
            #    # `ssh-keyscan github.com`. The public key for github.com is always implicitly
            #    # added.
            #    #ssh-known-hosts: ''

            #    # Whether to perform strict host key checking. When true, adds the options
            #    # `StrictHostKeyChecking=yes` and `CheckHostIP=no` to the SSH command line. Use
            #    # the input `ssh-known-hosts` to configure additional hosts.
            #    # Default: true
            #    #ssh-strict: ''

            #    # Whether to configure the token or SSH key with the local git config
            #    # Default: true
            #    #persist-credentials: 'true'

            #    # Relative path under $GITHUB_WORKSPACE to place the repository
            #    #path: 'randymcmillan'

            #    # Whether to execute `git clean -ffdx && git reset --hard HEAD` before fetching
            #    # Default: true
            #    clean: 'false'

            #    # Number of commits to fetch. 0 indicates all history for all branches and tags.
            #    # Default: 1
            #    fetch-depth: '0'

            #    # Whether to download Git-LFS files
            #    # Default: false
            #    lfs: 'false'

            #    # Whether to checkout submodules: `true` to checkout submodules or `recursive` to
            #    # recursively checkout submodules.
            #    #
            #    # When the `ssh-key` input is not provided, SSH URLs beginning with
            #    # `git@github.com:` are converted to HTTPS.
            #    #
            #    # Default: false
            #    submodules: 'recursive'
      - name: Setup Matrix
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: automate.sh matrix
        run: |
          cd $GITHUB_WORKSPACE
          python -c "import sys; print(sys.version)"
          make init
          make automate

  bitcoin-test-battery:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, self-hosted]
          #python-version: ['3.8', '3.9']
        python-version: ['3.9']
          #exclude:
          #  - os: ubuntu-latest
          #    python-version: ['2.7','3.6','3.7']
          #  - os: ubuntu-20.08
          #    python-version: ['2.7','3.6','3.7']
          #  - os: macos-latest
          #    python-version: ['2.7','3.6','3.7']
          #  - os: macos-10.15
          #    python-version: ['2.7','3.6','3.7']
          #  - os: windows-latest
          #    python-version: ['2.7','3.6','3.7']
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Setup Matrix
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: automate.sh matrix
        run: |
          cd $GITHUB_WORKSPACE
          python -c "import sys; print(sys.version)"
          ./bitcoin-test-battery.sh v22.0rc3

